import{a as S,S as q,i as s}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function f(o,t){return(await S.get("https://pixabay.com/api/",{params:{key:"55696654-5263066477aa053d936427b42",q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),v=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:c,comments:L,downloads:x})=>`
   <li class="gallery-item">
   <a class="gallery-link" href="${n}">
   <img class="gallery-img" src="${a}" alt="${e}" />
   </a>
   <div class="info">
   <p><b>Likes </b>${r}</p>
   <p><b>Views </b>${c}</p>
   <p><b>Comments </b>${L}</p>
   <p><b>Downloads </b>${x}</p>
   </div>
   </li>
  `).join("");u.insertAdjacentHTML("beforeend",t),v.refresh()}function w(){u.innerHTML=""}function p(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const P=document.querySelector(".form"),C=document.querySelector(".load-more");let i=1,l="";P.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),l===""){s.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"});return}i=1,w(),d(),p();try{const t=await f(l,i);t.hits.length===0?s.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"}):(g(t.hits),i*15>=t.totalHits?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"})):b())}catch{s.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"})}finally{y(),o.target.reset()}});C.addEventListener("click",async()=>{i+=1,d(),p();try{const o=await f(l,i);g(o.hits);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),i*15>=o.totalHits?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"})):b()}catch{s.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"})}finally{y()}});
//# sourceMappingURL=index.js.map
