import{a as v,S as w,i as c}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function u(o,t){return(await v.get("https://pixabay.com/api/",{params:{key:"55696654-5263066477aa053d936427b42",q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),x=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:b,downloads:L})=>`
   <li class="gallery-item">
   <a class="gallery-link" href="${i}">
   <img class="gallery-img" src="${s}" alt="${e}" />
   </a>
   <div class="info">
   <p><b>Likes </b>${r}</p>
   <p><b>Views </b>${n}</p>
   <p><b>Comments </b>${b}</p>
   <p><b>Downloads </b>${L}</p>
   </div>
   </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),x.refresh()}function S(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function q(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let a=1,d="";M.addEventListener("submit",async o=>{o.preventDefault(),d=o.target.elements["search-text"].value.trim(),a=1,S(),l(),y();try{const t=await u(d,a);t.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"}):(p(t.hits),a*15>=t.totalHits?(l(),c.error({message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"})):q())}catch(t){console.log(t)}finally{g(),o.target.reset()}});P.addEventListener("click",async()=>{a+=1,y();try{const o=await u(d,a);p(o.hits);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),a*15>=o.totalHits&&(l(),c.error({message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",messageColor:"#fff",position:"topRight",maxWidth:"432px"}))}catch(o){console.log(o)}finally{g()}});
//# sourceMappingURL=index.js.map
